version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: websec # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forewarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
